### ISSUE TITLE
Dll Download?

### ISSUE THREAD

**Issue by GHNJ** [NickAcPT/ModernUIDoneRight#2]
[creating this as an issue so folks can find it easier if they need the .dll] 

Issue: I'm not able to find the .dll file for this. Would you mind adding that to the repo? 

thanks!

**Comment by dustindog101** [comment]
exactlyy can you please upload a dll

**Comment by Creaous** [comment]
The download is located here:
#3

**Comment by NickAcPT** [comment]
Hello, I'm sorry I haven't addressed this earlier (more than a year ago sigh). But, the release of this project has always been on the releases tab.
