### ISSUE TITLE
DLL Download

### ISSUE THREAD

**Issue by Creaous** [NickAcPT/ModernUIDoneRight#3]
Current Version:
https://github.com/NickAcPT/ModernUIDoneRight/releases/download/latest/ModernUIDoneRight.dll

Future Versions:
https://github.com/NickAcPT/ModernUIDoneRight/releases/latest

**Comment by dustindog101** [comment]
who are you

**Comment by NickAcPT** [comment]
Thank you for trying to help newcomers, but since the release tab exists, this issue will not be very helpful.
